--- 
title: "CBC Workshop Series: R"
author: "Amjad Dabi, Sool (Will) Lee, Jolene Renek. Workshop modified from Julia Rager's Materials"
date: "Q1 2022"
site: bookdown::bookdown_site
documentclass: book
---

<br>

### Background
Conducting scientific research with the aid of computational tools are becoming the norm. Most of the latest technology utilizes computer language (e.g., R, Python, Java, C++, etc.) to answer their scientific questions. As we can see it from the title, we will going to briefly go over how we can utilize R to answer some of our scientific questions.

### Objectives
1. Downloading R/Rstudio
2. Basics of R + Tidyverse
3. Using Tidyverse
4. Creating Plots.
5. TBA
6. TBA

### Module Development Overview
Workshop modules were developed to provide the basics of writing a legible code, data organization, and analysis methods that can be used to address your scientific questions. Target audiences for these modules include students and professionals in academia, government, and industry that are interested in expanding and improving their skillset. Modules were developed by Julia Rager and have been modified by Sool (Will) Lee, Amjad Dabi, and Jolene Renek formatted for R/RStudio coding language. The first group of modules focused on introductory data science, which included the following topics: 

1. Setting up R/RStudio and coding in the R environment
2. Introduction to R and Tidyverse
3. Creating basic plots
4. Introduction to Dimensionality Reduction. 
5. Introduction to Clustering.

### Concluding Remarks
Together, we hope that these modules and resources serve as a cornerstone for your computer-aided scientific research
<br>
<br>

